### ISSUE TITLE
Missing December 31st

### ISSUE THREAD

**Issue by manuscrypt** [GoIlluminate/elm-fancy-daterangepicker#38]
Totally like your package, but unfortunately, the last day of the year seems to be missing: 
![image](https://user-images.githubusercontent.com/19311687/47601680-7e4bef80-d9d4-11e8-9f3a-8736bb5ef878.png)

**Comment by tlentz** [comment]
Fixed here: https://github.com/GoIlluminate/elm-fancy-daterangepicker/pull/39

Thanks for pointing out the issue
